---
- hosts: all
  become: true 

  tasks:
    - name: "shut down ubuntu machines"
      ansible.builtin.command:
        cmd: /sbin/shutdown -h now
      when: ansible_facts['os_family'] == "Debian"
        